### ISSUE TITLE
节点改名字后白屏

### ISSUE THREAD

**Issue by ArchibaldCoyner** [proxy-rock/proxy-rock#1]
改名字后点进去白屏,无法继续设置,也无法删除这个节点

**Comment by proxy-rock** [comment]
好像没有复现，有具体的系统版本、浏览器版本和操作步骤不，有的话麻烦提供下。

**Comment by snipertulip** [comment]
> 好像没有复现，有具体的系统版本、浏览器版本和操作步骤不，有的话麻烦提供下。

Windows11 21H2 22000.318
Chrome 已是最新版本
版本 124.0.6356.6（正式版本）dev （64 位）

这个问题出现在 [https://github.com/proxy-rock/proxy-rock/issues/4#issue-2189757955](url) 后。
控制台提示错误如下：
`
vendors.js:2 TypeError: s.map is not a function
    at Dn (dashboard.js:1:40770)
    at Co (vendors.js:2:931401)
    at El (vendors.js:2:943022)
    at Cs (vendors.js:2:989100)
    at yc (vendors.js:2:977385)
    at bc (vendors.js:2:977313)
    at fc (vendors.js:2:977176)
    at oc (vendors.js:2:973983)
    at ic (vendors.js:2:972538)
    at z (vendors.js:2:1029549)
`

**Comment by proxy-rock** [comment]
找到问题了 已发新版本
